version: '3.8'

services:
  gc-proxy-app:
    image: ghcr.io/keroger2k/gc-proxy:latest # Use the latest image from GitHub Container Registry
    container_name: gc-proxy-app
    ports:
      - '3000:3000' # Exposes port 3000 on the host
    environment:
      - MONGO_URL=mongodb://mongo:27017/gcdb # Connect to the mongo service
      - PORT=3000 # Port the app inside the container will listen on
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network: # Defines a custom bridge network
    driver: bridge
