name: Docker Image CI for GC Proxy

on:
  push:
    branches: ['main'] # Or "master", depending on your default branch
  pull_request:
    branches: ['main'] # Also build on PRs to main for testing

jobs:
  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # If you were using GitHub Container Registry (GHCR) instead of Docker Hub:
      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: keroger2k
          password: ${{ secrets.GH_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }} # Push only on merge to main
          tags: | # Replace with your Docker Hub username and image name
            keroger2k/gc-proxy-app:latest
            keroger2k/gc-proxy-app:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

